### ISSUE TITLE
ie11 에서 umd 포맷 실행 오류

### ISSUE THREAD

**Issue by min9nim** [madup-inc/lever-utils#6]
### Type
- [ ] New feature
- [x] Problem
- [ ] Enhancement
- [ ] Proposal

<br>

### Description
umd 포맷을 ie11 에서 실행할 때 구문오류 발생
https://unpkg.com/@madup-inc/utils@0.9.2/dist/index.umd.js

```js
!function(e, t) {
    "object" == typeof exports && "undefined" != typeof module ? t(exports) : "function" == typeof define && define.amd ? define(["exports"], t) : t((e || self).utils = {})
}(this, function(e) {
    var t = e=>null == e
      , n = e=>!t(e);
    e.classNames = function() {
        const e = [].slice.call(arguments).reduce((e,t)=>{
            if (!t)
                return e;
            if ("boolean" == typeof t)
                throw Error("Boolean type is not acceptable");
            return "string" == typeof t ? e + " " + t : e + Object.entries(t).reduce((e,[t,n])=>e + (n ? " " + t : ""), "")
        }
        , "");
        return e ? e.trim() : void 0
    }
    ,
    e.isIE = e=>{
        const t = e.userAgent.toLowerCase();
        return "Netscape" === e.appName && -1 !== t.indexOf("trident") || -1 !== t.indexOf("msie")
    }
    ,
    e.isNil = t,
    e.isNotNil = n,
    e.oneOf = (e,t)=>{
        const n = e.find(e=>"function" == typeof e[0] ? e[0]() : e[0])
          , r = n ? n[1] : t;
        return "function" == typeof r ? r() : r
    }
    ,
    e.parseSearchParams = e=>{
        const t = {}
          , n = e.indexOf("?") + 1;
        return e.slice(n).replace(/([^(?|#)=&]+)(=([^&]*))?/g, (e,n,r,i)=>{
            t[n] = decodeURIComponent(i)
        }
        ),
        t
    }
    ,
    e.randomStr = ()=>(65536 * (1 + Math.random()) | 0).toString(16),
    e.serializeSearchParams = (e={})=>Object.entries(e).map(([e,n])=>{
        if (t(n))
            return;
        let r = n;
        return Array.isArray(n) && (r = n.join(",")),
        e + "=" + encodeURIComponent(r)
    }
    ).filter(n).join("&"),
    e.toComma = e=>e ? Number(e).toLocaleString("ko-KR", {
        maximumSignificantDigits: 10
    }) : "0",
    e.toNumber = e=>e ? "number" == typeof e ? e : Number(String(e).replace(/,/gi, "")) : 0,
    e.validateBiznum = e=>{
        if (!e)
            return !1;
        const t = e.replace(/-/gi, "").split("").map(function(e) {
            return parseInt(e, 10)
        });
        if (10 === t.length) {
            const e = [1, 3, 7, 1, 3, 7, 1, 3, 5];
            let n = 0;
            return e.forEach(function(e, r) {
                n += e * t[r]
            }),
            n += parseInt(String(e[8] * t[8] / 10), 10),
            Math.floor(t[9]) === (10 - n % 10) % 10
        }
        return !1
    }
});
//# sourceMappingURL=index.umd.js.map
```

<br>

### Ref
- 관련 지라: N/A
- 관련 슬랙대화: N/A
- 기타 참조 링크: N/A

**Comment by min9nim** [comment]
1. browerList 설정 참고
    - https://github.com/browserslist/browserslist#configuring-for-different-environments
 1. 하지만 해당 프로젝트가 ie11까지 지원이 필요할 지는 별도로 고민이 필요

**Comment by gorillaKim** [comment]
> e.isIE = e=>{
>         const t = e.userAgent.toLowerCase();
>         return "Netscape" === e.appName && -1 !== t.indexOf("trident") || -1 !== t.indexOf("msie")
>     }

위 코드에서  리턴부분이 잘못된것 같습니다.
ie11 을 식별하는 코드가
```  "Netscape" === e.appName && -1 !== t.indexOf("trident") || -1 ```
이고 그 외 ie는 
``` -1 !== t.indexOf("msie") ```
입니다,

그래서 최종적으로 아래의 코드가 되어야 합니다.
```return ("Netscape" === e.appName && -1 !== t.indexOf("trident") ) || -1 !== t.indexOf("msie")```

**Comment by min9nim** [comment]
컴파일 중 괄호가 자동으로 빠져서 그런건데.. 
아마 결과는 같을 것 같아요.

**Comment by min9nim** [comment]
1. 하위 브라우져에서도 사용 가능하도록 ES5 스크립트로 빌드할 수 있으면 좋을 것 같다.
2. 그런데 폴리필들을 포함하면 스크립트 사이즈가 커질 수 있으므로 그냥 utils 에서도 ie11 지원을 포기하는 것도 나쁘지 않을 것 같다.

**Comment by min9nim** [comment]
원인)
isIE 가 화살표 함수로 정의되어 있어서 ie11 에서 실행이 불가한 상태였음

workaround)
isIE 함수만 ES5 스타일로 코딩

**Comment by min9nim** [comment]
1. isIE 만 ES5 스타일로 코딩하는 것은 의미없음. 다른 것들도 전부 화살표함수 대신 function 키워드로 함수를 정의하지 않으면 마찬가지 오류가 발생.
2. microbundle 빌드시 ES5 로 빌드하는 것은 가이드에서 권장하지 않음

![image](https://user-images.githubusercontent.com/6068828/122743283-d2ace780-d2c1-11eb-97a2-36c7944304a4.png)

**Comment by min9nim** [comment]
## utils 가 IE11 환경은 따로 지원하지 않는 것으로 잠정 결정

> isIE 함수를 크로스 프로젝트에서 브라우져에서 직접 사용할 수 있게 하여 얻는 이익보다, utils 가 IE11 지원을 위한 유지보수 비용이 더 많이 들어갈 것으로 예상되기 때문에
